#!/usr/bin/env python3
"""Generate skills/HOOKS_MAP.md — the one-page answer to "what hooks does this
repo wire, where do they live, what do they do".

Transcript mining (2026-06-12) found the same 8-file read chain (hook.sh +
install.sh across the hook skills) repeated identically in two sessions:
agents re-derive hook wiring by reading every file. This map is the pre-built
index; `index-first` points here. Regenerated by ./install.sh — do not edit.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
OUT = SKILLS / "HOOKS_MAP.md"

HOOK_EVENT_RE = re.compile(
    r"(UserPromptSubmit|PreCompact|PreToolUse|PostToolUse|SessionStart|Stop|SubagentStop)"
)


def settings_hooks() -> list[tuple[str, str]]:
    """(event, command) pairs from the repo-local .claude/settings.json."""
    out = []
    p = REPO / ".claude" / "settings.json"
    if not p.exists():
        return out
    try:
        cfg = json.loads(p.read_text())
    except json.JSONDecodeError:
        return out
    for event, entries in (cfg.get("hooks") or {}).items():
        for entry in entries or []:
            for h in entry.get("hooks") or []:
                cmd = h.get("command", "")
                if cmd:
                    out.append((event, cmd))
    return out


def skill_hook_inventory() -> list[dict]:
    """Every skill shipping hook tooling, whether wired or not."""
    rows = []
    for skill_dir in sorted(SKILLS.iterdir()):
        tools = skill_dir / "tools"
        if not skill_dir.is_dir() or not tools.is_dir():
            continue
        hook_files = sorted(
            str(f.relative_to(REPO))
            for f in tools.iterdir()
            if f.name in ("hook.sh", "hook.py")
        )
        if not hook_files:
            continue
        # Best-effort event detection from the skill's own docs/scripts
        text = ""
        skill_md = skill_dir / "SKILL.md"
        if skill_md.exists():
            text += skill_md.read_text(errors="ignore")
        for hf in hook_files:
            text += (REPO / hf).read_text(errors="ignore")
        events = sorted(set(HOOK_EVENT_RE.findall(text))) or ["?"]
        installer = tools / "install.sh"
        rows.append({
            "skill": skill_dir.name,
            "events": events,
            "entry": hook_files,
            "installer": str(installer.relative_to(REPO)) if installer.exists() else "",
        })
    return rows


def main() -> None:
    wired = settings_hooks()
    inventory = skill_hook_inventory()
    wired_by_skill = {}
    for event, cmd in wired:
        m = re.search(r"skills/([\w-]+)/tools/", cmd)
        if m:
            wired_by_skill.setdefault(m.group(1), []).append(event)

    lines = [
        "# Hooks map (generated — do not edit; `python3 scripts/gen_hooks_map.py`)",
        "",
        "One-page answer to \"what hooks exist / what's wired / where's the entry\".",
        "Read THIS instead of walking skills/*/tools/ file by file.",
        "",
        "| Skill | Hook event(s) | Wired here? | Entry | Installer |",
        "|---|---|---|---|---|",
    ]
    for r in inventory:
        wired_events = wired_by_skill.get(r["skill"], [])
        wired_cell = ", ".join(sorted(set(wired_events))) if wired_events else "no"
        lines.append(
            f"| {r['skill']} | {', '.join(r['events'])} | {wired_cell} "
            f"| {'<br>'.join(f'`{e}`' for e in r['entry'])} | `{r['installer']}` |"
        )
    lines += [
        "",
        "Wiring lives in `.claude/settings.json` (repo-local). Per-skill installers",
        "append hook entries and never delete; `./install.sh` prunes dead Brainer",
        "hooks on re-install. `output-filter` ships tooling but no auto-installer",
        "by design (wire as pipe or PostToolUse by hand).",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)} ({len(inventory)} hook skills, {len(wired)} wired entries)")


if __name__ == "__main__":
    main()
